//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalContentTypeCreator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExternalContentTypeCreator.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add external content type.
        /// </summary>
        internal static string ExternalLookup_ContentType_Add {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name.
        /// </summary>
        internal static string ExternalLookup_ContentType_DataSource_ColumnName {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_DataSource_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name in ECT.
        /// </summary>
        internal static string ExternalLookup_ContentType_DataSource_FieldName {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_DataSource_FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in ECT.
        /// </summary>
        internal static string ExternalLookup_ContentType_DataSource_Include {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_DataSource_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is key?.
        /// </summary>
        internal static string ExternalLookup_ContentType_DataSource_IsKey {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_DataSource_IsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- SELECT --.
        /// </summary>
        internal static string ExternalLookup_ContentType_DataSource_Select {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_DataSource_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source selection.
        /// </summary>
        internal static string ExternalLookup_ContentType_DataSource_Selection {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_DataSource_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available external content types.
        /// </summary>
        internal static string ExternalLookup_ContentType_List_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name for new ECT.
        /// </summary>
        internal static string ExternalLookup_ContentType_Name {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New external content type.
        /// </summary>
        internal static string ExternalLookup_ContentType_New_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External content types.
        /// </summary>
        internal static string ExternalLookup_ContentType_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ExternalLookup_ContentType_Type {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add data source.
        /// </summary>
        internal static string ExternalLookup_DataSource_Add {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source attributes.
        /// </summary>
        internal static string ExternalLookup_DataSource_Attributes {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication parameters.
        /// </summary>
        internal static string ExternalLookup_DataSource_Authentication_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Authentication_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFEXCON Configuration.
        /// </summary>
        internal static string ExternalLookup_DataSource_Configuration_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Configuration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string ExternalLookup_DataSource_Database {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        internal static string ExternalLookup_DataSource_DatabaseName {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available data sources.
        /// </summary>
        internal static string ExternalLookup_DataSource_List_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ExternalLookup_DataSource_Name {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a name for the new data source.
        /// </summary>
        internal static string ExternalLookup_DataSource_Name_Placeholder {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New data source.
        /// </summary>
        internal static string ExternalLookup_DataSource_New_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Store Application ID.
        /// </summary>
        internal static string ExternalLookup_DataSource_SecureStoreServiceId {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_SecureStoreServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        internal static string ExternalLookup_DataSource_ServerName {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR_SERVER\INSTANCE.
        /// </summary>
        internal static string ExternalLookup_DataSource_ServerName_Placeholder {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_ServerName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data sources.
        /// </summary>
        internal static string ExternalLookup_DataSource_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ExternalLookup_DataSource_Type {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Database.
        /// </summary>
        internal static string ExternalLookup_DataSource_Type_SQL {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Type_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ExternalLookup_General_Cancel {
            get {
                return ResourceManager.GetString("ExternalLookup_General_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string ExternalLookup_General_Delete {
            get {
                return ResourceManager.GetString("ExternalLookup_General_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ExternalLookup_General_Save {
            get {
                return ResourceManager.GetString("ExternalLookup_General_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        internal static string ExternalLookup_Link_Details {
            get {
                return ResourceManager.GetString("ExternalLookup_Link_Details", resourceCulture);
            }
        }
    }
}
