//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalContentTypeCreator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExternalContentTypeCreator.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add external content type.
        /// </summary>
        internal static string ExternalLookup_ContentType_Add {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name.
        /// </summary>
        internal static string ExternalLookup_ContentType_DataSource_ColumnName {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_DataSource_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name in ECT.
        /// </summary>
        internal static string ExternalLookup_ContentType_DataSource_FieldName {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_DataSource_FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in ECT.
        /// </summary>
        internal static string ExternalLookup_ContentType_DataSource_Include {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_DataSource_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is key?.
        /// </summary>
        internal static string ExternalLookup_ContentType_DataSource_IsKey {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_DataSource_IsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- SELECT --.
        /// </summary>
        internal static string ExternalLookup_ContentType_DataSource_Select {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_DataSource_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source selection.
        /// </summary>
        internal static string ExternalLookup_ContentType_DataSource_Selection {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_DataSource_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string ExternalLookup_ContentType_DataSource_Table {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_DataSource_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available external content types.
        /// </summary>
        internal static string ExternalLookup_ContentType_List_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name for new ECT.
        /// </summary>
        internal static string ExternalLookup_ContentType_Name {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New external content type.
        /// </summary>
        internal static string ExternalLookup_ContentType_New_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External content types.
        /// </summary>
        internal static string ExternalLookup_ContentType_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ExternalLookup_ContentType_Type {
            get {
                return ResourceManager.GetString("ExternalLookup_ContentType_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key column is not set..
        /// </summary>
        internal static string ExternalLookup_Creator_KeyColumn {
            get {
                return ResourceManager.GetString("ExternalLookup_Creator_KeyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add data source.
        /// </summary>
        internal static string ExternalLookup_DataSource_Add {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source attributes.
        /// </summary>
        internal static string ExternalLookup_DataSource_Attributes {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication parameters.
        /// </summary>
        internal static string ExternalLookup_DataSource_Authentication_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Authentication_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFEXCON Configuration.
        /// </summary>
        internal static string ExternalLookup_DataSource_Configuration_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Configuration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string ExternalLookup_DataSource_Database {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        internal static string ExternalLookup_DataSource_DatabaseName {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available data sources.
        /// </summary>
        internal static string ExternalLookup_DataSource_List_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ExternalLookup_DataSource_Name {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a name for the new data source.
        /// </summary>
        internal static string ExternalLookup_DataSource_Name_Placeholder {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New data source.
        /// </summary>
        internal static string ExternalLookup_DataSource_New_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Store Application ID.
        /// </summary>
        internal static string ExternalLookup_DataSource_SecureStoreServiceId {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_SecureStoreServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        internal static string ExternalLookup_DataSource_ServerName {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR_SERVER\INSTANCE.
        /// </summary>
        internal static string ExternalLookup_DataSource_ServerName_Placeholder {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_ServerName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data sources.
        /// </summary>
        internal static string ExternalLookup_DataSource_Title {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ExternalLookup_DataSource_Type {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Database.
        /// </summary>
        internal static string ExternalLookup_DataSource_Type_SQL {
            get {
                return ResourceManager.GetString("ExternalLookup_DataSource_Type_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ExternalLookup_General_Cancel {
            get {
                return ResourceManager.GetString("ExternalLookup_General_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string ExternalLookup_General_Delete {
            get {
                return ResourceManager.GetString("ExternalLookup_General_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ExternalLookup_General_Save {
            get {
                return ResourceManager.GetString("ExternalLookup_General_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials could not be retrieved from Secure Store Service..
        /// </summary>
        internal static string ExternalLookup_Helper_Credentials {
            get {
                return ResourceManager.GetString("ExternalLookup_Helper_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database string is not defined..
        /// </summary>
        internal static string ExternalLookup_Helper_Database {
            get {
                return ResourceManager.GetString("ExternalLookup_Helper_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login name does not include domain information..
        /// </summary>
        internal static string ExternalLookup_Helper_DomainMissing {
            get {
                return ResourceManager.GetString("ExternalLookup_Helper_DomainMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No LobSystemInstance available for LobSystem..
        /// </summary>
        internal static string ExternalLookup_Helper_LobSystem {
            get {
                return ResourceManager.GetString("ExternalLookup_Helper_LobSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider implementation for Secure Store Service can not be identified..
        /// </summary>
        internal static string ExternalLookup_Helper_Provider {
            get {
                return ResourceManager.GetString("ExternalLookup_Helper_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider type of secure store provider cannot be identified..
        /// </summary>
        internal static string ExternalLookup_Helper_ProviderType {
            get {
                return ResourceManager.GetString("ExternalLookup_Helper_ProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Store Application ID can not be identified..
        /// </summary>
        internal static string ExternalLookup_Helper_SecureStore {
            get {
                return ResourceManager.GetString("ExternalLookup_Helper_SecureStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server string is not defined..
        /// </summary>
        internal static string ExternalLookup_Helper_Server {
            get {
                return ResourceManager.GetString("ExternalLookup_Helper_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        internal static string ExternalLookup_Link_Details {
            get {
                return ResourceManager.GetString("ExternalLookup_Link_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields must be filled..
        /// </summary>
        internal static string ExternalLookup_Message_AllFields {
            get {
                return ResourceManager.GetString("ExternalLookup_Message_AllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must include the key column in the ECT..
        /// </summary>
        internal static string ExternalLookup_Message_IncludeKey {
            get {
                return ResourceManager.GetString("ExternalLookup_Message_IncludeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must not select more than one column as key..
        /// </summary>
        internal static string ExternalLookup_Message_KeyMaximum {
            get {
                return ResourceManager.GetString("ExternalLookup_Message_KeyMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select one column as key..
        /// </summary>
        internal static string ExternalLookup_Message_KeyMinimum {
            get {
                return ResourceManager.GetString("ExternalLookup_Message_KeyMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create external content type..
        /// </summary>
        internal static string ExternalLookup_Status_ContentType_Create {
            get {
                return ResourceManager.GetString("ExternalLookup_Status_ContentType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Content type could not be deleted..
        /// </summary>
        internal static string ExternalLookup_Status_ContentType_Delete {
            get {
                return ResourceManager.GetString("ExternalLookup_Status_ContentType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create external content type. An external content type with the same name is still in the cache..
        /// </summary>
        internal static string ExternalLookup_Status_ContentType_Duplicate {
            get {
                return ResourceManager.GetString("ExternalLookup_Status_ContentType_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No external content type available..
        /// </summary>
        internal static string ExternalLookup_Status_ContentType_None {
            get {
                return ResourceManager.GetString("ExternalLookup_Status_ContentType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content type could not be retrieved. Do you have the right permissions?.
        /// </summary>
        internal static string ExternalLookup_Status_ContentType_Permissions {
            get {
                return ResourceManager.GetString("ExternalLookup_Status_ContentType_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not access Business Data Connectivity service. Do you have the right permissions?.
        /// </summary>
        internal static string ExternalLookup_Status_DataSource_Access {
            get {
                return ResourceManager.GetString("ExternalLookup_Status_DataSource_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a connection to the data source..
        /// </summary>
        internal static string ExternalLookup_Status_DataSource_Connection {
            get {
                return ResourceManager.GetString("ExternalLookup_Status_DataSource_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create data source..
        /// </summary>
        internal static string ExternalLookup_Status_DataSource_Create {
            get {
                return ResourceManager.GetString("ExternalLookup_Status_DataSource_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source could not be deleted..
        /// </summary>
        internal static string ExternalLookup_Status_DataSource_Delete {
            get {
                return ResourceManager.GetString("ExternalLookup_Status_DataSource_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not access Business Data Connectivity service to list data sources..
        /// </summary>
        internal static string ExternalLookup_Status_DataSource_Listing {
            get {
                return ResourceManager.GetString("ExternalLookup_Status_DataSource_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data source available..
        /// </summary>
        internal static string ExternalLookup_Status_DataSource_None {
            get {
                return ResourceManager.GetString("ExternalLookup_Status_DataSource_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source could not be created. Do you have the right permissions?.
        /// </summary>
        internal static string ExternalLookup_Status_DataSource_Permissions {
            get {
                return ResourceManager.GetString("ExternalLookup_Status_DataSource_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data structure could not be loaded. Is the data source still valid and accessible?.
        /// </summary>
        internal static string ExternalLookup_Status_DataSource_Structure {
            get {
                return ResourceManager.GetString("ExternalLookup_Status_DataSource_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected data source is not available..
        /// </summary>
        internal static string ExternalLookup_Status_DataSource_Unavailable {
            get {
                return ResourceManager.GetString("ExternalLookup_Status_DataSource_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get credentials from Secure Store Service..
        /// </summary>
        internal static string ExternalLookup_Status_SecureStore_Credentials {
            get {
                return ResourceManager.GetString("ExternalLookup_Status_SecureStore_Credentials", resourceCulture);
            }
        }
    }
}
